--- #YAML:1.0
name:               Device-ELM327
version:            0.09
abstract:           Methods for reading OBD data with an ELM327 module.
author:
    - Alister Perrott <aperrott@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Device::SerialPort:  0
    Test::More:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
